<a href="https://colab.research.google.com/github/codingprahlad/Python-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array ([True,64,7.8])
print(arr)
print(type(arr))
print(arr.dtype)

[ 1.  64.   7.8]
<class 'numpy.ndarray'>
float64


In [ ]:
lis_1 = [2,3,7,8,9,3]
print(lis_1)
print(type(lis_1))

[2, 3, 7, 8, 9, 3]
<class 'list'>


In [ ]:
import numpy as np

lis_1 = [2,3,7,8,9,3]
print(lis_1)
print(type(lis_1))

new_list = np.array(lis_1)
print(new_list)
print(type(new_list))

[2, 3, 7, 8, 9, 3]
<class 'list'>
[2 3 7 8 9 3]
<class 'numpy.ndarray'>


In [ ]:
print(lis_1+[7,8,4])
print(new_list.ndim)
print(type(new_list))
print(new_list.size )
print(new_list.shape)
print()
print()


[2, 3, 7, 8, 9, 3, 7, 8, 4]
1
<class 'numpy.ndarray'>
6
(6,)




In [ ]:
import numpy as np
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(my_matrix)
print(type(my_matrix))
new_2 = np.array(my_matrix)
print(new_2)
print(type(new_2))
print(new_2.ndim)
print("The dimensions of array:",new_2.ndim)
print("The shape of array:",new_2.shape)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
<class 'list'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
The dimensions of array: 2
The shape of array: (3, 4)


In [ ]:

arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr1)
print(type(arr1))
a =list(arr1)
print(a)
print(type(a))


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
<class 'list'>


In [ ]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1 = np.array(arr1)
arr2= arr1[0][1][2]
print(arr2)



6


In [ ]:
arr1.shape

(2, 2, 3)

In [ ]:
import numpy as np
a = np.array ([1,2,3,4,5,6,7])
print(sum(a))
print(a.reshape(7,1))
print(a.reshape(-1))


28
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[1 2 3 4 5 6 7]


In [ ]:
a = 6
print(np.arange(a))


[0 1 2 3 4 5]


In [ ]:
zer = np.array([10])
print(np.zeros(zer))
print(np.zeros((5,5)))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
on = np.array ([5])
print(np.ones(on))
print(np.ones((8,3)))
print(np.ones((8,3,7)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
np.linspace(5,10,3)

array([ 5. ,  7.5, 10. ])

In [ ]:
line_space = np.array([2,10,5])

print(np.linspace(line_space[0],line_space[1],line_space[2],))

[ 2.  4.  6.  8. 10.]


In [ ]:
np.linspace(5,10,3,retstep=True)

(array([ 5. ,  7.5, 10. ]), np.float64(2.5))

In [ ]:
np.mean ([1,2,3,4,])

np.float64(2.5)

In [ ]:
import numpy as np


lis = pd.Series([52, 67, 82, 98, 72])
print(lis)
print(type(lis))


[2 4 6 5]
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd

tup = pd.Series([52, 67, 82, 98, 72])
print(tup)
print(type(tup))


0    52
1    67
2    82
3    98
4    72
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
import array as arr
a = arr.array("i", [64, 74, 83, 28])
print(a)
print(type(a))

array('i', [64, 74, 83, 28])
<class 'array.array'>


In [ ]:
import array as arr
b =arr.array ("f", [74, 8.9, 9.7, 99, 88])
print(*b)



74.0 8.899999618530273 9.699999809265137 99.0 88.0


In [ ]:
import array as arr
b =arr.array ("str", [ "rahlad", "parvez", "pursuhottam"])
print(*b)

NameError: name 'array' is not defined

In [ ]:
import array as arr

b = arr.array('u', ['a', 'b', 'c', 'd'])
print(*b)


a b c d


In [ ]:
import array as arr
a = arr.array ("b")

In [ ]:
import array as arr

a = arr.array('u', list("rahlad, parvez, pursuhottam"))
print(*a, )
a.reverse()
print(*a)
a.extend("danish, ramesh")


r a h l a d ,   p a r v e z ,   p u r s u h o t t a m
m a t t o h u s r u p   , z e v r a p   , d a l h a r


In [ ]:
import array as arr
a = arr.array("i", [64, 74, 83, 28])
print(a)
a.extend([73, 98, 76, 90])
print(*a)
a.reverse()
print(*a)
print(a.remove(76))

array('i', [64, 74, 83, 28])
64 74 83 28 73 98 76 90
90 76 98 73 28 83 74 64
None


In [ ]:
a = arr.array ('u', set{"rahlad, parvez, pursuhottam"})
print(*a)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-1882759874.py, line 1)

In [ ]:
import array as arr

a = arr.array('u', "rahlad parvez pursuhottam")
s = set(a)

print(s)


{'v', 'o', 's', 't', 'l', 'z', 'p', 'u', 'r', 'm', 'e', 'd', 'a', 'h', ' '}
